# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMensajecliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mensajecliente(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1440, 774)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("basth.rojasv@duocuc.cl")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("pelicanoprueba")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(5)").text == "Bienvenido/a basth.rojasv"
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5)").click()
  
