# Generated by Django 4.0.4 on 2022-05-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_producto', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField(blank=True)),
                ('imagen', models.ImageField(null=True, upload_to='img/')),
                ('categoria', models.IntegerField(choices=[[0, 'ninguno'], [1, 'Cuerdas'], [2, 'Percusión'], [3, 'Amplificadores'], [4, 'Accesorios']], null=True)),
            ],
        ),
    ]
